### ISSUE TITLE
Possible information leak

### ISSUE THREAD

**Issue by jtpgames** [JadKHaddad/Rusmpp#5]
The address `34.242.18.250:2775` in the examples points to a real server.
I can use `telnet` to connect to the IP and Port.

I recommend removing that from the examples or terminating the real server if it is your server.

**Comment by JadKHaddad** [comment]
`smscsim.smpp.org` points to `34.242.18.250`. 

For simplicity, I am not using DNS lookups in the examples. See [smpp-testing](https://smpp.org/smpp-testing-development.html)
